spring:
  application:
    name: proy-producto
  data:
    mongodb:
      uri: mongodb+srv://user-growth-dev:3Em6WjDzX7MYBHZ@fp-dqu-digital-mongo.aohi9.mongodb.net/master-dev?retryWrites=true&w=majority
